# Generated by Django 4.1.1 on 2022-09-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='team_part',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=100),
        ),
    ]
