# Generated by Django 4.1.1 on 2022-09-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyee',
            name='employee_id',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empolyee',
            name='hourly_rate',
            field=models.IntegerField(choices=[(15, '15'), (20, '20'), (30, '30')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empolyee',
            name='team',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
