# Generated by Django 4.1.1 on 2022-09-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_empolyee_team_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empolyee',
            name='employee_id',
        ),
    ]
