# Generated by Django 4.1.1 on 2022-09-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_work_arrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_leader_name', models.CharField(choices=[('Ramy', 'Ramy'), ('Hussam', 'Hussam'), ('Bahaa', 'Bahaa')], max_length=30)),
            ],
        ),
    ]
