# Generated by Django 3.2.12 on 2022-10-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_empolyee_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyee',
            name='work_arrangement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.work_arrangement'),
        ),
    ]
