# Generated by Django 3.2.12 on 2022-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_empolyee_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_employee',
            name='Team_one',
        ),
        migrations.RemoveField(
            model_name='team_employee',
            name='Team_three',
        ),
        migrations.RemoveField(
            model_name='team_employee',
            name='Team_two',
        ),
        migrations.AddField(
            model_name='empolyee',
            name='team_employee',
            field=models.ManyToManyField(null=True, to='employee.Team_employee'),
        ),
        migrations.AddField(
            model_name='team_employee',
            name='Team_employeef_name',
            field=models.CharField(choices=[('Team_one_employee', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Team_two_employee', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
