# Generated by Django 3.2.12 on 2022-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_team_employee_team_employeef_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_employee',
            name='Team_employeef_name',
        ),
        migrations.AddField(
            model_name='team_employee',
            name='Team_employee_category',
            field=models.CharField(choices=[('Team_one_employee', (('ramy', 'Ramy'), ('ezzat', 'Ezzat'), ('gamal', 'Gamal'))), ('Team_two_employee', (('hussam', 'Hussam'), ('saleh', 'Saleh'), ('sayed', 'Sayed'))), ('Team_three_employee', (('bahaa', 'Bahaa'), ('fady', 'Fady'), ('esraa', 'Esraa')))], default='', max_length=30),
            preserve_default=False,
        ),
    ]
